services:
  web:
    build: .  # Build the web container using the Dockerfile in the current directory
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    depends_on:
      - db  # Ensure DB starts before web
    env_file:
      - .env  # Load Flask and DB variables

  db:
    image: postgres:15  # Use PostgreSQL version 15
    restart: always  # Restart DB if it crashes
    env_file:
      - .env  # Make sure the DB picks up POSTGRES_PASSWORD, etc.
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent DB data

volumes:
  pgdata: {}  # Use Docker-managed volume